codenameone.displayName=Beber
codenameone.appId=com.hydratation.beber
codenameone.version=1.0
codenameone.packageName=com.hydratation.beber
codenameone.mainName=beber
codenameone.vendor=hydratation
codenameone.description=mon application mobile
codenameone.arg.ios.prerenderedIcon=true
codenameone.username=grymff@proton.me
codenameone.password=31Mai1970363257
